### ISSUE TITLE
华师 & DataEase 合作双周会议：2023-05-09

### ISSUE THREAD

**Issue by andyhuang18** [X-lab2017/open-wonderland#277]
# 会议
- 时间：12:00 ~ 13:00，2023/05/09
- 腾讯会议：**302-7883-3807**（<a href='https://meeting.tencent.com/dm/bH9EIBpFx5ow'>入会链接</a>）**请注意：会议链接已更新！**

# 议题

- [ ] 一期内容完成度确认 
- [ ] 区域对比大屏进度 @andyhuang18 @zhicheng-ning @PureNatural #244
- [ ] OSPO 大屏进度 @tyn1998 #250
- [ ] 基金会开源大屏进度 @longyanz #248
- [ ] XSOSI 优化 @zhicheng-ning #268
